theme: jekyll-theme-midnight
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      languages:  "Languages / Idiomas / Jezyki"
      lang: "en-US"
      title: "Mateusz Kimont"
      firstname: "Matt Kimont"
      description: "Senior Software Web Developer with 9 years experience.<br>Delivering High-Performance, Customized Web Solutions."
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      languages: "Languages / Idiomas / Jezyki"
      lang: "en-US"
      title: "Mateusz Kimont"
      firstname: "Matt Kimont"
      description: "Senior Software Web Developer with 9 years experience.<br>Delivering High-Performance, Customized Web Solutions."
