theme: jekyll-theme-midnight
show_downloads: false
languages: ["en", "pl", "es"]
default_lang: "en"
seo:
  json_ld: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en-US"
      title: "Mateusz Kimont - Principal Full-Stack Engineer"
      jobTitle: "Principal Full-Stack Engineer"
      fullname: "Mateusz Kimont"
      description: "Professional portfolio for Mateusz Kimont, a Principal Full-Stack Engineer with 8+ years of experience in PHP, AWS, and performance optimization. Open for new remote opportunities."
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      lang: "en-US"
      title: "Mateusz Kimont - Principal Full-Stack Engineer"
      jobTitle: "Principal Full-Stack Engineer"
      fullname: "Mateusz Kimont"
      description: "Professional portfolio for Mateusz Kimont, a Principal Full-Stack Engineer with 8+ years of experience in PHP, AWS, and performance optimization. Open for new remote opportunities."
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap