theme: jekyll-theme-midnight
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      languages:  "Languages / Idiomas / Jezyki"
      lang: "en-US"
      title: "Mateusz Kimont"
      firstname: "Matt Kimont"
      description: "Full stack web developer - remote, contract, part-hybrid only"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      languages: "Languages / Idiomas / Jezyki"
      lang: "en-US"
      title: "Mateusz Kimont"
      firstname: "Matt Kimont"
      description: "Full stack web developer - remote, contract, part-hybrid only"
  -
    scope:
      path: "php/*"
    values:
      layout: "page"
  -
    scope:
      path: "no-code/*"
    values:
      layout: "page"
  -
    scope:
      path: "devops/*"
    values:
      layout: "page"