theme: jekyll-theme-midnight
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en-US"
      title: "Mateusz Kimont - Principal Full-Stack Engineer"
      fullname: "Mateusz Kimont"
      description: "Full-Stack / Principal Engineer"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      lang: "en-US"
      title: "Mateusz Kimont - Principal Full-Stack Engineer"
      fullname: "Mateusz Kimont"
      description: "Full-Stack / Principal Engineer"
