theme: jekyll-theme-midnight
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      languages:  "Languages / Idiomas / Jezyki"
      lang: "en-US"
      title: "Mateusz Kimont"
      description: "Full stack web developer - remote only for hire"